#!/usr/bin/env bash
# =============================================================================
# local-prepare.sh — Build the React frontend for production deployment
# =============================================================================
# Run this from the MONOREPO ROOT before uploading files to BigRock.
#
# Usage:
#   VITE_API_BASE_URL=https://yourdomain.com/api bash laravel-backend/scripts/local-prepare.sh
#
# Or with a subdomain:
#   VITE_API_BASE_URL=https://api.yourdomain.com bash laravel-backend/scripts/local-prepare.sh
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FRONTEND_DIR="$REPO_ROOT/artifacts/corporate-academy"
DIST_DIR="$FRONTEND_DIR/dist/public"

echo ""
echo "================================================="
echo "  Corporate Academy — Local Build Preparation"
echo "================================================="
echo ""

# ── Validate VITE_API_BASE_URL ─────────────────────────────────────────────────
if [ -z "${VITE_API_BASE_URL:-}" ]; then
  echo "ERROR: VITE_API_BASE_URL is not set."
  echo ""
  echo "Usage:"
  echo "  VITE_API_BASE_URL=https://yourdomain.com/api bash $0"
  echo "  VITE_API_BASE_URL=https://api.yourdomain.com bash $0"
  exit 1
fi

echo "API Base URL: $VITE_API_BASE_URL"
echo ""

# ── Write .env.production ──────────────────────────────────────────────────────
ENVFILE="$FRONTEND_DIR/.env.production"
cat > "$ENVFILE" <<EOF
# Generated by local-prepare.sh — $(date -u '+%Y-%m-%dT%H:%M:%SZ')
VITE_API_BASE_URL=$VITE_API_BASE_URL
EOF
echo "Wrote: $ENVFILE"
echo ""

# ── Build the frontend ─────────────────────────────────────────────────────────
echo "Building React frontend..."
cd "$REPO_ROOT"
BASE_PATH=/ PORT=3000 pnpm --filter @workspace/corporate-academy run build
echo ""

# ── Verify output ──────────────────────────────────────────────────────────────
if [ ! -f "$DIST_DIR/index.html" ]; then
  echo "ERROR: Build failed — $DIST_DIR/index.html not found."
  exit 1
fi

echo "Build output:"
ls -lh "$DIST_DIR" | head -20
echo ""

# ── Copy SPA .htaccess into dist ───────────────────────────────────────────────
HTACCESS_SRC="$REPO_ROOT/laravel-backend/scripts/public_html.htaccess"
HTACCESS_DST="$DIST_DIR/.htaccess"
if [ -f "$HTACCESS_SRC" ]; then
  cp "$HTACCESS_SRC" "$HTACCESS_DST"
  echo "Copied .htaccess → $HTACCESS_DST"
fi
echo ""

# ── Summary ──────────────────────────────────────────────────────────────────
echo "================================================="
echo "  ✓ Local build complete!"
echo "================================================="
echo ""
echo "Upload the following to public_html/ on your BigRock server:"
echo "  $DIST_DIR/"
echo ""
echo "You can use rsync (recommended — includes hidden files like .htaccess):"
echo "  rsync -avz --delete $DIST_DIR/ user@yourdomain.com:~/public_html/"
echo ""
echo "Or with scp (note the trailing /. to include dotfiles):"
echo "  scp -r $DIST_DIR/. user@yourdomain.com:~/public_html/"
echo ""
echo "Or create a tar archive for upload via cPanel File Manager:"
echo "  tar -czf /tmp/corporate-academy-dist.tar.gz -C $DIST_DIR ."
echo "  # Upload /tmp/corporate-academy-dist.tar.gz and extract in cPanel"
echo ""
