<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    public $timestamps = false;

    protected $table = 'web_courses';

    // protected $fillable = [
    //     'slug',
    //     'title',
    //     'category_slug',
    //     'category_name',
    //     'level',
    //     'summary',
    //     'description',
    //     'duration_hours',
    //     'mode',
    //     'price',
    //     'rating',
    //     'total_rating',
    //     'enrolled',
    //     'featured',
    //     'skills',
    //     'image_url',
    //     'curriculum',
    //     'faq',
    // ];

    protected $fillable = [
    'course_clone_id',
    'title',
    'offer',
    'enrolled',
    'description',
    'slug',
    'level',
    'seo_page',
    'checked_seo_page',
    'related_courses',
    'related_courses_side',
    'rating',
    'total_rating',
    'course_type',
    'duration_hours',
    'mode',
    'price',
    'featured',
    'skills',
    'course_curriculum',
    'clone_course_curriculum',
    'seo_type',
    'show_category',
    'course_image_name',
    'courses_module',
    'course_duration',
    'course_week_days',
    'course_weekend',
    'course_fasttrack',
    'live_project',
    'professional_trained',
    'batches_every_month',
    'top_heading',
    'top_description',
    'course_name',
    'city',
    'certificate',
    'category',
    'category_slug',
    'category_name',
    'subcategory',
    'course_pdf_text',
    'coursecurriculumexcel',
    'courseaboutexcel',
    'video_link',
    'meta_title',
    'meta_keyword',
    'meta_description',
    'course_defination',
    'course_popular',
    'exam_title',
    'exam_text',
    'format',
    'certification_type',
    'delivery_method',
    'certification_time',
    'certification_cost',
    'language',
    'why_learn',
    'why_learn_heading',
    'FAQs',
    'faqq',
    'faqa',
    'testimonial',
    'testimonial_visibility',
    'related_certifications',
    'show_certification_tab',
    'show_front_page',
    'show_top_menu',
    'show_on_footer',
    'footer_certificate',
    'footer_top_course',
    'show_trending_courses',
    'batch_visibility',
    'certification_visibility',
    'status',
    'ip_address',
    'geo_city',
    'geo_latitude',
    'geo_longitude',
    'geo_country',
    'geo_ipaddress',
    'created_by',
    'updated_by',
    'updated_date',
    'deleted_by',
    'show_front_second',
];
    protected $casts = [
        'duration_hours' => 'integer',
        'price'          => 'integer',
        'rating'         => 'float',
        'total_rating'   => 'integer',
        'enrolled'       => 'integer',
        'featured'       => 'boolean',
        'skills'         => 'array',
        'curriculum'     => 'array',
        'faq'            => 'array',
    ];
}
